version: '3.8'

services:
  backend:
    image: ghcr.io/zakiehmn/django-app:$TAG_NAME
    environment:
      - FRONT_URL="https://www.hamahangsho.ir"
      - ALLOWED_HOSTS="https://api.hamahangsho.ir"
      - SECRET_KEY=$SECRET_KEY
      - DEBUG="True"
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/db

  frontend:
    image: ghcr.io/elnazbashirian/front:$TAG_NAME
    container_name: vue_app
    ports:
      - "8080:80"
    restart: always


volumes:
  sqlite_data:
