# Generated by Django 5.1.4 on 2025-02-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Specific Dates'), (1, 'Days of Week')], default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventDayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنج\u200cشنبه'), (4, 'جمعه'), (5, 'شنبه'), (6, 'یکشنبه')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_of_week', to='scheduler.event')),
            ],
        ),
    ]
