# Generated by Django 5.1.4 on 2025-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('attendee', 'start_time'), name='unique_attendee_start_time'),
        ),
    ]
