# Generated by Django 5.1.4 on 2025-02-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_event_event_type_eventdayofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeekAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField(choices=[(0, '0:00'), (1, '1:00'), (2, '2:00'), (3, '3:00'), (4, '4:00'), (5, '5:00'), (6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')])),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week_availabilities', to=settings.AUTH_USER_MODEL)),
                ('event_day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduler.eventdayofweek')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificDateAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_date_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AddConstraint(
            model_name='dayofweekavailability',
            constraint=models.UniqueConstraint(fields=('attendee', 'event_day_of_week', 'start_hour'), name='unique_attendee_day_of_week_time'),
        ),
        migrations.AddConstraint(
            model_name='specificdateavailability',
            constraint=models.UniqueConstraint(fields=('attendee', 'start_time'), name='unique_attendee_specific_date_time'),
        ),
    ]
